name: safety_tourist_app
description: "Tourist Safety App - Live tracking, maps, panic button , geofencing"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Map and location
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  
  # HTTP and storage
  http: ^1.2.2
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  crypto: ^3.0.3
  
  # State management
  provider: ^6.1.2
  
  # Background services
  flutter_background_service: ^5.0.8
  flutter_local_notifications: ^19.4.2
  wakelock_plus: ^1.3.3
  permission_handler: ^12.0.1
  
  # Feedback and alerts
  vibration: ^3.1.4
  
  # Device and app information
  device_info_plus: ^12.1.0
  package_info_plus: ^8.3.1
  battery_plus: ^6.0.1
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package